project:
  type: website
  output-dir: docs

website:
  title: "Neuroscience of Language"

  sidebar:
    collapse-level: 1
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Overview
      - requirements.qmd
      - readings.md
      - policies.qmd
      - resources.qmd
  page-navigation: true


#brite
#united

format:
  html:
    theme: yeti
    css: styles.css
    toc: true


# - section: "Schedule"
#        href: schedule.md
#        contents:
#          - unit_1.qmd
#          - unit_2.qmd
#          - unit_3.qmd
#          - unit_4.qmd
#          - unit_5.qmd
