project:
  type: website
  output-dir: docs

website:
  title: "Neuroscience of Language"

  sidebar:
    style: docked
    search: true
    contents:
      - href: syllabus.md
        text: Overview
      - requirements.qmd
      - schedule.md
      - readings.md
      - policies.qmd


format:
  html:
    theme: pulse
    css: styles.css
    toc: true