---
title: "LING-2801: Neuroscience of Language"
---

| | | 
| --- | --- |
| **Professor** | Heidi Getz, Ph.D. [heidi.getz@georgetown.edu](mailto:heidi.getz@georgetown.edu) <br> Poulton Hall 223 (Linguistics), Building D, Room 154 (Neurology)  | 
| **Class schedule** | Tues/Thurs 9:30-10:45  | 
| **Office hours** | TBD  | 
| **Prerequisites** | None  | 
| **Required texts** | Brennan, J. R. (2022). *Language and the brain: a slim guide to neurolinguistics*. Oxford University Press. [Link to purchase text at bookstore](https://georgetown.bncollege.com/course-material-listing-page?utm_campaign=storeId=88131_langId=-1_courseData=LING_2801_01_F26&utm_source=wcs&utm_medium=registration_integration) <br>Additional readings will be provided.

<br>

## Course Description

This is an introductory course on language and the brain, designed for students with no background in neuroscience. Its goal is to introduce students to the major scientific findings in this area as well as the scientific process that generated this evidence. Topics include the brain regions and networks involved in language processing in the healthy brain; how these structures develop in children; and how language skills are affected by damage to these structures.

## Science for All

This course fulfills Georgetown's *Science for All* core requirement. I designed the course around the learning goals of that program. According to the [*Science for All* website](https://sfa.georgetown.edu/): 

> The primary goal of courses specifically designed to fulfill the core science requirement will not be to provide a summary of current knowledge in a particular discipline, but instead to illustrate, in the context of a scientific discipline, how scientific understanding is developed, tested, and revised. 

In this course, you will learn about language in the brain by studying the scientific research that led to our current understanding of this topic. There will be some traditional lectures, in which I provide conceptual background or historical context for a topic. But we will also spend a substantial amount of time unpacking and understanding specific studies. You’ll also watch demonstrations of specific research methodologies, practice evaluating and interpreting scientific evidence, and interview some of the scientists who conduct research on the neuroscience of language at Georgetown.

A secondary goal of the SFA program is this:

> In addition, Science For All courses will help and encourage students to understand better the significant role that science plays in their daily lives, and will include examples of the use of scientific methods in addressing complex social problems and of the ethical issues that science can raise. 

Throughout the course we’ll consider issues within the neuroscience of language that have broad social relevance. We’ll start by discussing the core scientific principle of functional localization—the idea that specific cognitive functions, like language, are handled by particular specific brain regions—along with the problematic and unscientific ways in which this idea has been interpreted throughout history. Other important topics will include signed languages and their neural representation (spoiler: it’s basically the same as for spoken languages); language networks in language-deprived individuals (i.e., profoundly Deaf people who had no access to a signed language until after childhood); and the neural and cognitive characteristics of language networks in multilingual people. 


## Learning Goals

The course is designed to achieve the following overall learning outcomes:

* Knowledge of the basic principles, foundational evidence, and current research challenges in the field of language and the brain  
* Understanding of the scientific process through which researchers learn about this field  
* The ability to understand and interpret scientific evidence about language in the brain  
* An understanding of how research on language and the brain relates to broader societal issues

Unit-specific learning goals are listed on their respective pages; see [schedule](schedule.md).