---
title: "Course Requirements"
---
| Weight | Assignment |
| -- | -- | -- | -- | -- |
| Ungraded | [Preparation](#reading) |
| 2% | [Attendance & participation](#participation) |
| 48%| [Exams](#exams) |
| 16%| [Group work in class](#papers)  |
| 30% |[Controversy Investigation](#paper) |
| 3%| [Researcher interview](#interview)  |
| 1%| [Researcher panel](#panel)|

<p>

## Preparation {#reading}
You will pretty much always need to do something to prepare for class. Usually, this is a reading, though I'll also occasionally ask you to listen to an episode of [The Language Neuroscience Podcast](https://langneurosci.org/podcast/) or watch a video. 

There will be two types of readings. The specific readings are listed on that unit's page on the course site (see [Schedule](schedule.md)).

1. Background readings: I'll assign chapters from the Brennan text, encyclopedia articles, or similar sources to provide general background on a topic. Some of the material in these readings will be reinforced in class, but *all* of the material is fair game for the exams.

2. Scientific articles: We'll also read some primary literature (real scientific papers). These will be dense and technical. It is very important to review these papers before class; otherwise, you will struggle to contribute to your group's in-class work. But don't worry if (when) there are parts you don't understand. We will work through the papers together in class.

Hard copies of the articles will be handed out in class. You may reference these hard copies, along with any notes you've written on them, during in-class [exams](#exams).


::: {.callout-tip}
# Tips for reading scientific papers
When reviewing the scientific articles, I strongly recommend following the process here: [**Guide to reading scientific papers**](https://hrgetz.github.io/guide.html). We'll go over this in class.
:::

## Attendance & participation {#participation}

We will take formal attendance. Multiple unexcused absences will affect your individual participation grade *and also your individual grade for your small group's in-class work during that unit*, see below. 

During class, I'll occasionally ask you to respond to questions in real time using a polling tool like Mentimeter. Your answers to these questions will not be graded for correctness, but repeated failure to participate in the polls will affect your participation grade. 


## Exams {#exams}

There will be four in-person exams (including the final), each worth roughly 12% of your grade. Exam dates and grade percentages are tentative. If one exam ends up covering a longer span of the course than others, grade weighting will be adjusted accordingly. I will tell you ahead of time about any changes.

Tentative exam dates for each unit are listed on the corresponding unit page (see [schedule](schedule.md)). The exact timing of the exams may be adjusted depending on course needs. The fourth exam will take place on the date that the Registrar has set for our class.

During exams, you are allowed to reference the printed copies of any primary sources (scientific articles)[^primarylit] that we covered during that unit, including any notes you have written on those copies. You are also allowed to reference a printed [summary sheet](https://docs.google.com/document/d/1a4gz3wIFyBtgsPicKq_pLwk5VNVqK_yg-sUg-GYwf7A/edit?tab=t.0).

[^primarylit]: Primary sources are indicated on the schedule pages with this icon: []{.my-badge .article}

::: {.callout-note}
# What's on the exams? 
**The exams are designed to measure your progress towards the specific learning goals that are listed on each unit's page.** In general, they are meant to assess your knowledge of foundational concepts, your ability to evaluate and interpret scientific evidence about language and the brain. 
They will cover lecture material, background readings, and the primay literature that we worked through in class.
:::

## Group work on scientific papers {#papers}

A significant portion of class will be dedicated to small group work.

Sometimes, you will work together to practice applying concepts from the readings/lectures. Other times, you will work with your group members to understand and interpret evidence from the scientific papers on the reading list. For example, you may be asked to create a visual aid showing how a study worked, or to use a brain atlas to visualize which brain regions were active during a particular experiment. 

Some of the work will be graded as complete/incomplete. Other work will be graded on a standard letter grade scale. I'll try to let you know ahead of time how grading will work for a particular activity, but if it's not clear, just ask.

For each of the four main course units (see [schedule](schedule.md)), you'll be in a different group. At the end of that unit the group will receive a grade for their work during that unit. Each of your small group grades is worth 4% of your course grade (4% x 4 units = 16% total). 

Everyone in the group gets the same grade, unless there are consistent issues with an individual member's contributions. Examples of issues that would affect an individual member's grade include unexcused absences, failure to prepare for group work by doing the readings, or lack of engagement in the group's discussion. If there is an issue with any student's contributions, please let us know as soon as possible so that we can help address it. 

## Controversy Investigation {#paper}

See [here](controversy.qmd). 

## Researcher Interview {#interview}

For this assignment, you will conduct a structured interview with one of the predoctoral or postdoctoral scholars in Georgetown’s [Neuroscience of Language training program](https://neurolang.georgetown.edu/). The goal of your interview will be to learn about a specific research question that this person is trying to answer; to understand the research approach or method that they are trying to use in order to answer it; and to identify some things that make it challenging to conduct this type of research. After the interview, you will briefly describe to your classmates the researcher’s main question and research approach, and you will submit a written reflection. 

::: {.callout-note collapse="true" appearance=simple}
# Detailed guidance for researcher interview
(To be added: Tips for conducting the interview, instructions for written reflection)

:::

## Researcher Panel {#panel}

At the end of the semester, we will host a panel discussion with Neuroscience of Language researchers at various stages of their career, ranging from graduate students to senior professors. The focus of this panel will be on the future of the field: we’ll ask researchers where they think the field is going and what challenges the field faces. To prepare for this, I will ask each student to submit some questions for panelists in advance, and then the class will vote on which questions to present to the panelists. You will also submit a written reflection afterwards.

::: {.callout-note collapse="true" appearance=simple}

# Detailed guidance for researcher panel
(To be added: Link for question submission; Instructions for written reflection)
:::

