---
title: "Foundation"
---
::: {.callout-tip collapse=true}
# Learning goals for this unit

**Course**

1. Know who your professor is  
2. Know how I will assess your mastery of course content

**Brain anatomy**

1. Name and identify
    a) the components of the Central Nervous System
    b) the two cerebral hemishperes
    c) the four lobes of the brain
2. Roughly locate Broca's area and Wernicke's area on a side view of the brain
3. Identify *coronal*, *axial*, and *sagittal* views of the human brain and tell which way a brain is "facing" on each view
4. Identify *gyri*, *sulci*, *white matter*, and *grey matter* on a brain cross-section
5. Locate the following major sulci on an image of the brain's surface: *longitudinal*, *central*, *lateral* 
6. (In progress) "Navigate" to a region of the brain using the following neuroanatomical and directional terms: *frontal*, *temporal*, *parietal*, *occipital*, *anterior*, *posterior*, *inferior*, *superior*, *lateral*, *medial*, *sulcus*, *gyrus*, *left*, *right*

**Basic principles & foundational evidence**

1. Understand the sense in which language is a type of computation and give an example
1. Define the following terms: *localization*, *lateralization*, *aphasia*
1. Describe the characteristics of language production and comprehension that are traditionally associated with non-fluent and fluent aphasia
1. Describe the "Classic Model" of language in the brain and explain the 19th-century evidence for this model

**The toolbox**

1. Explain the logic of the lesion/deficit mapping method
1. Describe two methods that can be used to assess lateralization of language

**Scientific inquiry**

1. Distinguish evidence, inferences, and ideas in scientific text
1. For the following claim, (a) describe scientific evidence that supports the claim; (b) explain why the evidence supports the claim; and (c) explain to someone's grandparents why anyone should care
    * Language processing in humans is lateralized to the left hemisphere.
:::


| Date | Class Topic | Due |
| -- | -- | -- | -- |
| Thurs 8/27 | Course Introduction [][1]{.my-badge .slides} |  [Baggio 2022](https://drive.google.com/file/d/1N_GbrPWy_zkyM8BYVG33PeRk2NOkZm27/view?usp=drive_link){.my-badge .reading} | 
| Tues 9/1 | Language as computation [][2]{.my-badge .slides} [][1b]{.my-badge .group}|
| Thurs 9/3 | Brain anatomy [][3]{.my-badge .slides} |  [<u>SGN</u> p. 18-25]{.my-badge .reading}
| Fri 9/4 || [Pick a controversy](controversy.qmd#project-timeline){.my-badge .controversy}
| Tues 9/8 | *No class (Monday schedule)* | | 
| Thurs 9/10 | Localization of function, classical model [][4]{.my-badge .slides} [][aphasia-lab]{.my-badge .group}| [<u>SGN</u> p. 10-15, 27-31]{.my-badge .reading} <br>[Geschwind 1970 p. 940-941](https://drive.google.com/drive/folders/1pZBhxxiW7N0s8KQqUXg5bnKWopzKVloB){.my-badge .reading} (until "Pure Alexia without Agraphia")|
| Fri 9/11 || [AI use policy](controversy.qmd#project-timeline){.my-badge .controversy}
| Tues 9/15 | Sign language aphasia [][5]{.my-badge .slides} [][sign-aphasia]{.my-badge .group}<br>Dr. Carolyn Gershman, Gallaudet University | [Hickok et al. 1998](https://drive.google.com/drive/folders/1pZBhxxiW7N0s8KQqUXg5bnKWopzKVloB){.my-badge .reading}
| Thurs 9/17 |  Lateralization [][6]{.my-badge .slides} [][lateralization]{.my-badge .group}| [MacNeilage et al. 2009](https://drive.google.com/drive/folders/1pZBhxxiW7N0s8KQqUXg5bnKWopzKVloB){.my-badge .reading} |
| Friday 9/19 | | *Nothing due* 
| Tues 9/22 | [Exam #1]{.exam} *exam date is tentative, may change* | [EXAM](https://docs.google.com/document/d/1xqyKwzCgk0IGJtY-chgaHPRHnAcvainx24OzlT1st_Y/edit?usp=sharing){.hidden-notes}

[1]:https://docs.google.com/presentation/d/1S-twq_R9KZWHKwUxCgpskvh7g66OaMdo1Z-OYOKt820/edit
[2]:https://docs.google.com/presentation/d/1jyQqxVLcxgUTMdSuKAvVXysoGkv5phrmmoFLspAKKng/edit
[3]:https://docs.google.com/presentation/d/1-DlaIOIvnQBYJNo8rJH51RvTGDmv6JFJAnk2MSbpzUQ/edit
[4]:https://docs.google.com/presentation/d/1-ezBcrR7-fW8k9VVZgU28ZpjAFoxlYTB2a67PofzSqo/edit?slide=id.p#slide=id.p
[5]:https://docs.google.com/presentation/d/1b5J07ecFhEIT58eD0hmq3WWEVxPnfBgvdifn58McDXs/edit?usp=drive_link
[6]:https://docs.google.com/presentation/d/1aS6poppc09Fypp4Ub3aRg-zq64Uw7RE2-BWze0dV_30/edit?usp=drive_link


[1b]:https://docs.google.com/document/d/1rYZkeWmhq1jtN8ckGgFqgmBk5MRXNYAwweAFwiElkcc/edit?usp=sharing
[sign-aphasia]:https://docs.google.com/document/d/1lqhqWg9VGqi6wzA5ZMdcxttDT20q3hTus7QmmpZhFNA/edit?usp=sharing
[aphasia-lab]:https://docs.google.com/document/d/10pV8_HSjHNJk7lSvG4jE5r8w6J8mQPEM4iiF9-8xlVo/edit?usp=sharing
[lateralization]:https://docs.google.com/document/d/1qXTEAr-P_95p3-Ipb0321RJA_Br20GRZg8knywfbZGw/edit?usp=sharing

[Mentimeter Poll Results, Unit 1](mentis_1.qmd){.menti-button}


:::: {.unit-card-row}
{{< include _includes/legend.qmd >}}

::: {.unit-card}


**Resources**  

Anatomy:  
[BrainFacts.org Interactive 3D Brain Viewer](https://www.brainfacts.org/3d-brain)  
[Neurotorium brain atlas](https://neurotorium.org/tool/brain-atlas/)  
[UBC: The Cortex](https://www.neuroanatomy.ca/modules/Cortex/story.html)  
[Showercap Mindmap activity](https://journals.physiology.org/doi/full/10.1152/advan.00095.2011)  
[Neuroscientifically Challenged](https://www.youtube.com/@neurochallenged)  

History of the field:  
[Race & Popular Science in Early America](https://www.youtube.com/watch?v=sLKTS6dZ7Bw)  
[TLNP #11: Dr. Levelt](https://langneurosci.org/podcast/)

Aphasia:  
[Aphasia (NIDCD)](https://www.nidcd.nih.gov/health/aphasia)  
[Aphasia simulations](https://vohadmin.github.io/Aphasia_Sim/)  
[UBC Aphasia Videos](https://neuroanatomy.ca/modules/Language/story.html)

:::
::::
