---
title: "The language network"
---

::: {.callout-tip collapse=true}
# Learning goals for this unit

**Brain anatomy**

1. Identify *gyri*, *sulci*, *white matter*, and *grey matter* on a brain cross-section
1. Identify *coronal*, *axial*, and *sagittal* views of the human brain and tell which way a brain is "facing" on each view
1. State the main regions of the brain that are involved in language processing, using neuroanatomical and directional terms, and locate these regions on saggital, coronal, and axial slices of the brain

**The toolbox**

1. Explain in simple terms what is measured by fMRI and PET studies
1. Explain the logic of the subtraction method
1. Given a figure showing brain activation in an fMRI or PET study:
    a) State which view of the brain is being shown
    b) Indicate which way the brain is "facing"
    c) Explain what the colors represent
1. Use a brain atlas to translate between XYZ coordinates and anatomical landmarks

**Scientific explanation**

1. Explain how the classical model of language in the brain would need to be expanded and revised in order to account for the evidence presented in Binder et al. (1997) and Petitto et al (2001)
1. For the following claims, (a) describe scientific evidence that supports the claim; (b) explain why the evidence supports the claim; and (c) explain why anyone cares
    * The general brain regions used for language processing are consistent across individuals.
    * The neural organization of language is similar for spoken and signed languages.
:::


| Date | Topic | Due |
| -- | -- |  -- |
| Thurs 9/24 | Methods [][7]{.my-badge .slides}| [<u>SGN</u> p. 25-27; 31-34]{.my-badge .reading} <br>[*Understanding fMRI* [Video], 17:18-28:46](https://youtu.be/eN-zCoI_Ejc?si=9aW_mQXIhsTvH1Vm&t=1038){.my-badge}
| Friday 9/25 || <small>Suggestion: Start working on your secondary sources</small>
| Tues 9/29 | Tour of [CFMI](https://cfmi.georgetown.edu/) |
| Thurs 10/1 | Expanding the classical model;<br>the subtraction method [][8]{.my-badge .slides} [][binder-design]{.my-badge .group}| [Binder et al. 1997 p. 353-355](https://drive.google.com/drive/folders/1pZBhxxiW7N0s8KQqUXg5bnKWopzKVloB){.my-badge .article}<br>(Abstract, Introduction, Materials and Methods)
| Friday 10/2 || [Secondary sources](controversy.qmd#project-timeline){.my-badge .controversy}
| Tues 10/6 | Expanding the classical model;<br>WATB (What Are The Blobs?) [][9]{.my-badge .slides} [][binder-results]{.my-badge .group}| [Binder et al. 1997 p. 355-362](https://drive.google.com/drive/folders/1pZBhxxiW7N0s8KQqUXg5bnKWopzKVloB){.my-badge .article}<br>(Results, Discussion)
| Thurs 10/8 | Scientific explanation;<br>sign language aphasia [][sign-aphasia]{.my-badge .group} |[Hickok et al. 1998](https://drive.google.com/drive/folders/1pZBhxxiW7N0s8KQqUXg5bnKWopzKVloB){.my-badge .reading}
| Friday 10/9 | | [Primary sources](controversy.qmd#project-timeline){.my-badge .controversy}
| Tues 10/13 | Expanding the classical model;<br>Speech vs. sign [][10]{.my-badge .slides} [][petitto-design]{.my-badge .group}|  [Petitto et al. 2000 p. 13961-13963](https://drive.google.com/drive/folders/1pZBhxxiW7N0s8KQqUXg5bnKWopzKVloB){.my-badge .article}<br>(Abstract, Introduction, Methods)
| Thurs 10/15 |  Activation in 3D [][11]{.my-badge .slides} [][petitto-results]{.my-badge .group} |[Petitto et al. 2000 p. 13963-13966](https://drive.google.com/drive/folders/1pZBhxxiW7N0s8KQqUXg5bnKWopzKVloB){.my-badge .article}<br>(Results, Discussion)|  
| Friday 10/16 | |[Summary #1](controversy.qmd#project-timeline){.my-badge .controversy}
| Tues 10/20 | Visit anatomy lab |
| Thurs 10/22 | [Exam #2]{.exam} | [EXAM](https://docs.google.com/document/d/1xqyKwzCgk0IGJtY-chgaHPRHnAcvainx24OzlT1st_Y/edit?usp=sharing){.hidden-notes}

[7]: https://docs.google.com/presentation/d/1E6KJ8ZANM8UWZCWrT2yUDB9bsuFqEFv2FSDQAYcYaSs/edit?usp=drive_link
[8]: https://docs.google.com/presentation/d/1OF3vQvqHdez7yOyLC89PxaUPbzD0EITDRsRl_dkVMsc/edit?usp=drive_link
[9]: https://docs.google.com/presentation/d/1OFH-VlWe3JxYhou-okT6FD757rVabvqQFQd2mMgrCvA/edit?usp=drive_link
[10]:https://docs.google.com/presentation/d/1fe8GV5iBIoJfMWF1bk2yDWBOqVyg3Esz9ZkA-qvKJ9I/edit?usp=drive_link
[11]:https://docs.google.com/presentation/d/1VcpT2mQG-eJe2xaEpM2LhYLInEsmlXOksULvLj1TvVQ/edit?usp=drive_link
[sign-aphasia]:https://docs.google.com/document/d/1lqhqWg9VGqi6wzA5ZMdcxttDT20q3hTus7QmmpZhFNA/edit?usp=sharing

[binder-design]:https://docs.google.com/document/d/1tB7TSaKqlnxp8rVoyu9QKd5sbeMeGPO9fPZZspR7lYE/edit?usp=sharing
[binder-results]:https://docs.google.com/document/d/1Euw5AG_98JECPEHlOdrIktrR7o-zulq7j3cE4pust0M/edit?usp=sharing
[petitto-design]:https://docs.google.com/document/d/1v8hgEy7usRbeEEq1ZRp5XTxtIywYwN2DdrpUUENIWbY/edit?usp=sharing
[petitto-results]:https://docs.google.com/document/d/1kayVgqPngIeSWhMT4GvK6mtzJVOho3TyFN12stMG5Lc/edit?usp=sharing


:::: {.unit-card-row}
{{< include _includes/legend.qmd >}}
::: {.unit-card}

**Resources**

[HRG's guide to reading scientific papers](https://hrgetz.github.io/guide.html)
[Abbreviations, from <u>SGN</u>](abbreviations.qmd)  

fMRI:  
[What is fMRI?](https://www.youtube.com/watch?v=4UOeBM5BwdY) (4.5 minutes)  
[Dr. Pylkkanen's lecture on fMRI](https://www.youtube.com/watch?v=ZuZV9Pq7fSg&list=PLwW-nea-Z6h-TiG0rBIviCQ5XaTyGq5WQ&index=9) (19 minutes)  

Interpreting brain activation maps:  
[Neurosynth](https://neurosynth.org/)  
[NeuroVault](https://neurovault.org/)  
[BrainMap](https://www.brainmap.org/)  
[MNI <-> Talairach Converter](https://bioimagesuiteweb.github.io/webapp/mni2tal.html)  
:::
::::